[package]
name = "grpc-tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.13.5"
tokio = "1.45.0"
tokio-stream = "0.1.17"
tonic = "0.13.1"

[build-dependencies]
tonic-build = "0.13.1"